import { Client } from '@modelcontextprotocol/sdk/client/index.js'
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js'
import { fileURLToPath } from 'url'
import { dirname, resolve } from 'path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const projectRoot = resolve(__dirname, '..')
const smokePort = process.env.SMOKE_UI_PORT || '3334'

function log(msg: string): void {
  process.stderr.write(`[smoke-mcp] ${msg}\n`)
}

const transport = new StdioClientTransport({
  command: 'node',
  args: ['server/index.ts'],
  cwd: projectRoot,
  env: { ...process.env, UI_PORT: smokePort } as Record<string, string>,
  stderr: 'inherit'
})

const client = new Client({ name: 'smoke-mcp', version: '1.0.0' })

let exitCode = 0
try {
  log(`spawning server on UI_PORT=${smokePort}`)
  await client.connect(transport)

  const tools = await client.listTools()
  const toolNames = tools.tools.map((t) => t.name)
  log(`listTools → ${JSON.stringify(toolNames)}`)

  const expected = ['open-dashboard', 'add-plan']
  const missing = expected.filter((name) => !toolNames.includes(name))
  if (missing.length) {
    throw new Error(`missing expected tools: ${missing.join(', ')}`)
  }

  const result = await client.callTool({
    name: 'add-plan',
    arguments: {
      fileName: 'smoke-test.md',
      content: '# Smoke Test\n\nThis plan is generated by scripts/smoke-mcp.ts.\n'
    }
  })
  log(`add-plan → ${JSON.stringify(result)}`)

  if ('isError' in result && result.isError) {
    throw new Error(`add-plan returned isError=true`)
  }

  log('OK — both tools responded with valid MCP results')
} catch (err) {
  log(`FAIL — ${err instanceof Error ? err.message : String(err)}`)
  exitCode = 1
} finally {
  await client.close().catch(() => {})
  await transport.close().catch(() => {})
  process.exit(exitCode)
}
